# Generated by Django 4.0.4 on 2022-06-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Random_Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quote', models.CharField(max_length=2000)),
                ('Author', models.CharField(default='Unknown', max_length=1000)),
            ],
        ),
    ]
