# Generated by Django 3.2.9 on 2021-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Random_Quotes',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Quote', models.CharField(max_length=10000000000)),
            ],
        ),
    ]
