# Generated by Django 3.0.8 on 2021-12-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_quotes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
