# Generated by Django 3.0.8 on 2021-12-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0002_auto_20211231_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_quotes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
