# Generated by Django 4.0.4 on 2022-06-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0004_random_quotes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_quotes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
